language: node_js
node_js: "7"
sudo: required
dist: trusty
git:
   depth: 9999999
install:
  - npm cache clean
  - npm install
script:
  - npm run test
  - npm run build
before_deploy:
  - cd build
deploy:
  provider: azure_web_apps
  verbose: true
  on: develop
  skip_cleanup: true 
